---
- name: Check k0s installation status
  command: which kubectl
  changed_when: false
  register: k0s_installed
# ---
- name: Install k0s
  become: true
  when: k0s_installed is changed
  ansible.builtin.shell: curl -sSLf https://get.k0s.sh | sudo sh
# ---
- name: Start k0s
  become: true
  when: k0s_installed is changed
  ansible.builtin.shell: sudo k0s install controller --single
# ---
