---
- name: Install nerdctl
  become: true
  ansible.builtin.shell: curl -L -o /home/kj/nerdctl-1.5.0.tar.gz "https://github.com/containerd/nerdctl/releases/download/v1.5.0/nerdctl-1.5.0-linux-amd64.tar.gz"
# ---
- name: Unarchive nerdctl
  become: yes
  unarchive:
    src: nerdctl-1.5.0.tar.gz
    dest: /home/kj
    creates: /home/kj/nerdctl-1.5.0
  when: tomb_archive is changed
  register: unarchived
# ---
- name: Copy nerdctl bin to /usr/bin
  ansible.builtin.copy:
    src: /home/kj/nerdctl-1.5.0/nerdctl
    dest: /usr/bin/nerdctl
    mode: "0755"
# ---
- name: Copy nerdctl.toml to /etc
  ansible.builtin.copy:
    src: ./files/nerdctl.toml
    dest: /etc/nerdctl/nerdctl.toml
    mode: "0644"
# ---
- name: Cleanup nerdctl
  ansible.builtin.file:
    state: absent
    path: "{{ nerd_item }}"
  with_items:
    - /home/kj/nerdctl-1.5.0.tar.gz
    - /home/kj/nerdctl-1.5.0/
  loop_control:
    loop_var: nerd_item
