---
- name: Check nerdctl installation status
  command: which nerdctl
  failed_when: false
  register: nerdctl_installed
# ---
- block:
    - name: Install nerdctl
      ansible.builtin.shell: curl -L -o "{{ lookup('env', 'HOME') }}"/nerdctl-1.5.0.tar.gz "https://github.com/containerd/nerdctl/releases/download/v1.5.0/nerdctl-1.5.0-linux-amd64.tar.gz"
    # ---
    - name: Unarchive nerdctl
      unarchive:
        src: nerdctl-1.5.0.tar.gz
        dest: "{{ lookup('env', 'HOME') }}"
        creates: "{{ lookup('env', 'HOME') }}/nerdctl-1.5.0"
    # ---
    - name: Copy nerdctl bin to /usr/bin
      ansible.builtin.copy:
        src: "{{ lookup('env', 'HOME') }}/nerdctl-1.5.0/nerdctl"
        dest: /usr/bin/nerdctl
        mode: "0755"
    # ---
    - name: Copy nerdctl.toml to /etc
      ansible.builtin.copy:
        src: ./files/nerdctl.toml
        dest: /etc/nerdctl/nerdctl.toml
        mode: "0644"
    # ---
    - name: Cleanup nerdctl
      ansible.builtin.file:
        state: absent
        path: "{{ nerd_item }}"
      with_items:
        - "{{ lookup('env', 'HOME') }}/nerdctl-1.5.0.tar.gz"
        - "{{ lookup('env', 'HOME') }}/nerdctl-1.5.0/"
      loop_control:
        loop_var: nerd_item
  become: true
  check_mode: false
  when: nerdctl_installed.rc != 0
