- when: target | length == 0
  block:
    - ansible.builtin.debug:
        msg: No target specified for "exists" role | ending play...
    - ansible.builtin.meta: end_play
###
- when: target | length > 0
  block:
    - name: Check if {{ target }} exists
      ansible.builtin.command: which {{ target }}
      failed_when: false
      changed_when: false
      register: result
    - name: Set fact about {{ target }}
      ansible.builtin.set_fact:
        exists_{{ target }}: "{{ result.rc }}"
