- name: Clone dotfiles from github
  ansible.builtin.git:
    repo: https://github.com/KJone1/dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/DEV/dotfiles"
    version: master
  register: dotfiles_repo_clone
  failed_when:
    - sddm_repo_clone.failed
    - not 'Local modifications exist in ' in dotfiles_repo_clone.msg
  notify: Run dotfiles install script
