- name: Clone dotfiles from github
  ansible.builtin.git:
    repo: https://github.com/KJone1/dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/DEV/dotfiles"
    version: master
# ---
- name: Run dotrfiles install script
  ansible.builtin.script: "{{ lookup('env', 'HOME') }}/DEV/dotfiles/install.sh"
