- become: true
  vars:
    version: "v0.15.1"
  check_mode: false
  block:
    - name: Ensure temp buildkit directory
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/buildkit"
        state: directory
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: "0755"
    # ---
    - name: Install buildkit
      ansible.builtin.shell: curl -L -o "{{ lookup('env', 'HOME') }}/buildkit/buildkit.tar.gz" "https://github.com/moby/buildkit/releases/download/{{ version }}/buildkit-{{ version }}.linux-amd64.tar.gz"
    # ---
    - name: Unarchive buildkit
      ansible.builtin.unarchive:
        src: "{{ lookup('env', 'HOME') }}/buildkit/buildkit.tar.gz"
        dest: "{{ lookup('env', 'HOME') }}/buildkit"
        extra_opts:
          - --strip=1
          - --no-anchored
          - buildkitd
          - buildctl
    # ---
    - name: Copy buildkit bin to /usr/bin
      ansible.builtin.copy:
        src: "{{ lookup('env', 'HOME') }}/buildkit/{{ buildkit_item }}"
        dest: /usr/bin/{{ buildkit_item }}
        mode: "0755"
      loop:
        - buildkitd
        - buildctl
      loop_control:
        loop_var: buildkit_item
    # ---
    - name: Ensure /etc/buildkit directory
      ansible.builtin.file:
        path: "/etc/buildkit"
        state: directory
    # ---
    - name: Copy buildkit.toml to /etc
      ansible.builtin.copy:
        src: buildkitd.toml
        dest: /etc/buildkit/buildkit.toml
        mode: "0644"
    # ---
    - name: Copy buildkit service file
      ansible.builtin.copy:
        src: buildkit.service
        dest: /etc/systemd/system/buildkit.service
        mode: "0644"
    # ---
    - name: Run systemd daemon_reload
      ansible.builtin.systemd:
        daemon_reload: true
    # ---
    - name: Cleanup buildkit
      ansible.builtin.file:
        state: absent
        path: "{{ lookup('env', 'HOME') }}/buildkit/"
