- become: true
  check_mode: false
  block:
    - name: Install kubectl
      ansible.builtin.shell: curl -L -o /usr/bin/kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    # ---
    - name: Set kubectl file permissions
      ansible.builtin.file:
        path: /usr/bin/kubectl
        owner: kj
        group: kj
        mode: "0755"
