# - ansible.builtin.include_role:
#     name: exists
#   vars:
#     target: "{{ exists_var }}"
#   with_items:
#     - k0s
#     - k9s
#     - kubectl
#     - nerdctl
#     - buildkitd
#   loop_control:
#     loop_var: exists_var

- ansible.builtin.include_tasks: k0s.yaml
- ansible.builtin.include_tasks: k9s.yaml
- ansible.builtin.include_tasks: kubectl.yaml
- ansible.builtin.include_tasks: nerdctl.yaml
- ansible.builtin.include_tasks: buildkit.yaml
