- become: true
  vars:
    version: "v1.7.2"
  check_mode: false
  block:
    - name: Ensure nerdctl directory
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/nerdctl"
        state: directory
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: "0755"
    # ---
    - name: Install nerdctl
      ansible.builtin.shell: curl -L -o "{{ lookup('env', 'HOME') }}/nerdctl/nerdctl.tar.gz" "https://github.com/containerd/nerdctl/releases/download/{{ version }}/nerdctl-{{ version | trim(chars='v') }}-linux-amd64.tar.gz"
    # ---
    - name: Unarchive nerdctl
      ansible.builtin.unarchive:
        src: "{{ lookup('env', 'HOME') }}/nerdctl/nerdctl.tar.gz"
        dest: "{{ lookup('env', 'HOME') }}/nerdctl"
        mode: "0755"
    # ---
    - name: Copy nerdctl bin to /usr/bin
      ansible.builtin.copy:
        src: "{{ lookup('env', 'HOME') }}/nerdctl/nerdctl"
        dest: /usr/bin/nerdctl
        mode: "0755"
    # ---
    - name: Ensure /etc/nerdctl directory
      ansible.builtin.file:
        path: "/etc/nerdctl"
        state: directory
    # ---
    - name: Copy nerdctl.toml to /etc
      ansible.builtin.copy:
        src: nerdctl.toml
        dest: /etc/nerdctl/nerdctl.toml
        mode: "0644"
    # ---
    - name: Cleanup nerdctl
      ansible.builtin.file:
        state: absent
        path: "{{ lookup('env', 'HOME') }}/nerdctl/"
