- name: Install standard packages
  become: true
  ansible.builtin.dnf:
    name:
      - code
      - helm
      - vlc
      - solaar
      - neovim
      - qbittorrent
      - wireguard-tools
      - thunar
      - sway
      - wl-clipboard
      - grimshot
      - fd-find
      - lazygit
      - ripgrep
      - bat
      - nnn
    state: latest
