- name: Install standard packages
  become: true
  ansible.builtin.dnf:
    name:
      - code
      - helm
      - vlc
      - solaar
      - neovim
      - qbittorrent
      - wireguard-tools
      - thunar
      - wl-clipboard
      - grimshot
    state: latest
