- name: Enable copr repo for lazygit
  community.general.copr:
    name: atim/lazygit
    state: enabled
- name: Install standard packages
  become: true
  ansible.builtin.dnf:
    name:
      - code
      - helm
      - vlc
      - solaar
      - neovim
      - qbittorrent
      - wireguard-tools
      - thunar
      - sway
      - wl-clipboard
      - grimshot
      - fd-find
      - lazygit
      - ripgrep
      - bat
      - nnn
      - stow
    state: latest
