- become: true
  block:
    - name: Add rpm fusion repo
      ansible.builtin.shell: dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
    # ---
    - name: Fix broken ffmpeg installation
      ansible.builtin.shell: dnf swap ffmpeg-free ffmpeg --allowerasing
