- name: Add flathub as flatpak repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    state: present
- name: Install flatpak
  ansible.builtin.package:
    name: flatpak
    state: latest
- name: Install flatpak packages
  community.general.flatpak:
    name:
      - com.discordapp.Discord
      - io.github.flattool.Warehouse
      - net.nokyan.Resources
