---
- name: Check brave installation status
  command: which brave-browser
  failed_when: false
  changed_when: false
  register: brave_installed
# ---
- block:
    - name: Install dnf-plugins-core
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present
    # ---
    - name: Add brave repo
      ansible.builtin.shell: dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    # ---
    - name: Import brave rpm
      ansible.builtin.shell: rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    # ---
    - name: Install brave
      ansible.builtin.dnf:
        name:
          - brave-browser
          - brave-keyring
        state: present
  become: true
  check_mode: false
  when: brave_installed.rc != 0
