---
# - name: Return motd to registered var
#   ansible.builtin.command: rpm --import https://packages.microsoft.com/keys/microsoft.asc
#   become: yes

# - name: Return motd to registered var
#   ansible.builtin.command: 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
#   become: yes

- name: install vscode
  become: true
  ansible.builtin.dnf:
    name: code
    state: present
