---
- name: add rpm fusion repo
  become: true
  ansible.builtin.shell: dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
# ---
- name: install standard packages
  become: true
  ansible.builtin.dnf:
    name:
      - code
      - helm
      - vlc
      - solaar
      - neovim
    state: present
# ---
- name: install kubectl
  become: true
  ansible.builtin.shell: curl -L -o /home/kj/.local/bin/kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
# ---
- name: set kubectl file permissions
  become: true
  ansible.builtin.file:
    path: /home/kj/.local/bin/kubectl
    owner: kj
    group: kj
    mode: "0751"
