---
- name: Check terraform installation status
  command: which terraform
  failed_when: false
  changed_when: false
  register: terraform_installed
# ---
- block:
    - name: Install dnf-plugins-core
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present
    # ---
    - name: Add terraform repo
      ansible.builtin.shell: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    # ---
    - name: Install terraform
      ansible.builtin.dnf:
        name:
          - terraform
        state: present
    # ---
    - name: Download terraform-docs
      ansible.builtin.shell: curl -sSLo "{{ lookup('env', 'HOME') }}"/terraform-docs.tar.gz https://terraform-docs.io/dl/v0.16.0/terraform-docs-v0.16.0-$(uname)-amd64.tar.gz
    # ---
    - name: Install terraform-docs
      ansible.builtin.unarchive:
        src: "{{ lookup('env', 'HOME') }}/terraform-docs.tar.gz"
        dest: "/usr/bin/"
        owner: kj
        group: kj
        mode: "0751"
    # ---
    - name: Cleanup terraform-docs
      ansible.builtin.file:
        state: absent
        path: "{{ lookup('env', 'HOME') }}/terraform-docs.tar.gz"
    # ---
  become: true
  check_mode: false
  when: terraform_installed.rc != 0
