---
- name: Check tomb installation status
  command: which tomb
  failed_when: false
  changed_when: false
  register: tomb_installed
# ---
- block:
    - name: get tomb
      get_url:
        url: https://files.dyne.org/tomb/releases/Tomb-2.10.tar.gz
        dest: "{{ lookup('env', 'HOME') }}/"
    # ---
    - name: Ensure Tomb directory
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/Tomb-2.10"
        state: directory
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
    # ---
    - name: Unarchive tomb
      unarchive:
        src: "{{ lookup('env', 'HOME') }}/Tomb-2.10.tar.gz"
        dest: "{{ lookup('env', 'HOME') }}/Tomb-2.10"
    # ---
    - name: Install tomb dependencies
      ansible.builtin.dnf:
        name:
          - make
          - steghide
        state: present
    # ---
    - name: Run 'make install' for tomb
      make:
        chdir: "{{ lookup('env', 'HOME') }}/Tomb-2.10"
        target: install
    # ---
    - name: Cleanup tomb
      ansible.builtin.file:
        state: absent
        path: "{{ tomb_item }}"
      with_items:
        - "{{ lookup('env', 'HOME') }}/Tomb-2.10.tar.gz"
        - "{{ lookup('env', 'HOME') }}/Tomb-2.10/"
      loop_control:
        loop_var: tomb_item
  become: true
  check_mode: false
  when: tomb_installed.rc != 0
