---
- name: Setup workstation
  hosts: all
  # ---
  tasks:
    - name: Find yaml files in tasks folder
      ansible.builtin.find:
        paths: "../tasks/"
        patterns: "*.yaml,*.yml"
        recurse: yes
        excludes: "facts.yaml"
      register: tasks_found
    # ---
    - include_tasks: "{{ task.path }}"
      loop: "{{ tasks_found.files }}"
      loop_control:
        loop_var: task
