---
- name: Setup workstation
  hosts: all
  # ---
  tasks:
    - name: Find yaml files in tasks folder
      ansible.builtin.find:
        paths: "../tasks/"
        patterns:
          - "*.yaml"
          - "*.yml"
        recurse: true
        excludes:
          - "facts.yaml"
      register: tasks_found
    # ---
    - ansible.builtin.include_tasks: "{{ task.path }}"
      no_log: true
      loop: "{{ tasks_found.files }}"
      loop_control:
        loop_var: task
